-- database/seeds.sql
-- Sample seed data for ProVenture: Freelancers, Clients, Services, and Reviews
-- Standard account password: password123
USE cshub;

-- Disable foreign key checks for clean insertion
SET FOREIGN_KEY_CHECKS = 0;
TRUNCATE TABLE reviews;
TRUNCATE TABLE services;
SET FOREIGN_KEY_CHECKS = 1;

-- 1. Users (Admins, Freelancers, Clients)
INSERT INTO users (name, email, password, phone, role) VALUES ('Administrator', 'admin@cshub.com', '$2y$10$Cvk5Qb/4ZmROE8oa1/6iEO/PQ.1IgZAZX7HAvsNFHwOBqYLbZofmm', '60123456789', 'admin') ON DUPLICATE KEY UPDATE name = VALUES(name), phone = VALUES(phone), role = VALUES(role);
INSERT INTO users (name, email, password, phone, role) VALUES ('Ayman Aqasyah', 'aymanaqasyah1@gmail.com', '$2y$12$aCWctNFxbGD1xHxd7qm16OXx0SB2kXMRY/akBeG2UFgL1j.DTfYOa', '601129392419', 'freelancer') ON DUPLICATE KEY UPDATE name = VALUES(name), phone = VALUES(phone), role = VALUES(role);
INSERT INTO users (name, email, password, phone, role) VALUES ('John Doe', 'johndoe@yahoo.com', '$2y$10$QQMLEJvjZIfEVRyJ7fzfKe4mo4Q9oPCpFBmN6D7Qtajj6GOVZCRfW', '012345678', 'client') ON DUPLICATE KEY UPDATE name = VALUES(name), phone = VALUES(phone), role = VALUES(role);
INSERT INTO users (name, email, password, phone, role) VALUES ('Ali bin Ahmad', 'aliahmad@gmail.com', '$2y$12$aCWctNFxbGD1xHxd7qm16OXx0SB2kXMRY/akBeG2UFgL1j.DTfYOa', '60123456789', 'client') ON DUPLICATE KEY UPDATE name = VALUES(name), phone = VALUES(phone), role = VALUES(role);
INSERT INTO users (name, email, password, phone, role) VALUES ('Haji Kassim', 'hjkassim@gmail.com', '$2y$10$r2cZy3HRxTOXMLB/xpbxvuRSvYh/UvWgw/xDr3yiNGHhRUKi7i23y', '01234567890', 'freelancer') ON DUPLICATE KEY UPDATE name = VALUES(name), phone = VALUES(phone), role = VALUES(role);
INSERT INTO users (name, email, password, phone, role) VALUES ('akmal bin halim', 'akmalhalim@gmail.com', '$2y$10$lj/5aHnOGjykp6fNo0HF6OJVV//ne190RxT9408NJbgt9yxW.ljGC', '0123456789', 'client') ON DUPLICATE KEY UPDATE name = VALUES(name), phone = VALUES(phone), role = VALUES(role);
INSERT INTO users (name, email, password, phone, role) VALUES ('osman bin mohamad', 'osmanmohamad@gmail.com', '$2y$10$udXklMZeBC6YXa6Htc7dSekTuZpIeJvV7pUIezPjHV6wM0trlVuHi', '0123456789', 'freelancer') ON DUPLICATE KEY UPDATE name = VALUES(name), phone = VALUES(phone), role = VALUES(role);
INSERT INTO users (name, email, password, phone, role) VALUES ('John Doe', 'johndoe1@gmail.com', '$2y$10$46Pt1bUhrT4mLc9yQ9svO.dwHfT8PWtlom.l2EmSWGJZe4Cyv2T6W', '6012345678', 'freelancer') ON DUPLICATE KEY UPDATE name = VALUES(name), phone = VALUES(phone), role = VALUES(role);
INSERT INTO users (name, email, password, phone, role) VALUES ('Ahmad Kamil', 'ahmad.kamil@cshub.com', '$2y$12$aCWctNFxbGD1xHxd7qm16OXx0SB2kXMRY/akBeG2UFgL1j.DTfYOa', '601123456781', 'freelancer') ON DUPLICATE KEY UPDATE name = VALUES(name), phone = VALUES(phone), role = VALUES(role);
INSERT INTO users (name, email, password, phone, role) VALUES ('Nurul Hidayah', 'nurul.hidayah@cshub.com', '$2y$12$aCWctNFxbGD1xHxd7qm16OXx0SB2kXMRY/akBeG2UFgL1j.DTfYOa', '60178901234', 'freelancer') ON DUPLICATE KEY UPDATE name = VALUES(name), phone = VALUES(phone), role = VALUES(role);
INSERT INTO users (name, email, password, phone, role) VALUES ('Kevin Tan', 'kevin.tan@cshub.com', '$2y$12$aCWctNFxbGD1xHxd7qm16OXx0SB2kXMRY/akBeG2UFgL1j.DTfYOa', '60123498765', 'freelancer') ON DUPLICATE KEY UPDATE name = VALUES(name), phone = VALUES(phone), role = VALUES(role);
INSERT INTO users (name, email, password, phone, role) VALUES ('Hafiz Ramli', 'hafiz.ramli@cshub.com', '$2y$12$aCWctNFxbGD1xHxd7qm16OXx0SB2kXMRY/akBeG2UFgL1j.DTfYOa', '60134567890', 'freelancer') ON DUPLICATE KEY UPDATE name = VALUES(name), phone = VALUES(phone), role = VALUES(role);
INSERT INTO users (name, email, password, phone, role) VALUES ('Farah Nabilah', 'farah.nabilah@cshub.com', '$2y$12$aCWctNFxbGD1xHxd7qm16OXx0SB2kXMRY/akBeG2UFgL1j.DTfYOa', '60198765432', 'freelancer') ON DUPLICATE KEY UPDATE name = VALUES(name), phone = VALUES(phone), role = VALUES(role);
INSERT INTO users (name, email, password, phone, role) VALUES ('Danial Lee', 'danial.lee@cshub.com', '$2y$12$aCWctNFxbGD1xHxd7qm16OXx0SB2kXMRY/akBeG2UFgL1j.DTfYOa', '60167890123', 'freelancer') ON DUPLICATE KEY UPDATE name = VALUES(name), phone = VALUES(phone), role = VALUES(role);
INSERT INTO users (name, email, password, phone, role) VALUES ('Siti Sarah', 'siti.sarah@cshub.com', '$2y$12$aCWctNFxbGD1xHxd7qm16OXx0SB2kXMRY/akBeG2UFgL1j.DTfYOa', '60182345678', 'freelancer') ON DUPLICATE KEY UPDATE name = VALUES(name), phone = VALUES(phone), role = VALUES(role);
INSERT INTO users (name, email, password, phone, role) VALUES ('Priyadarshini Mohan', 'priya.mohan@cshub.com', '$2y$12$aCWctNFxbGD1xHxd7qm16OXx0SB2kXMRY/akBeG2UFgL1j.DTfYOa', '60145678901', 'freelancer') ON DUPLICATE KEY UPDATE name = VALUES(name), phone = VALUES(phone), role = VALUES(role);
INSERT INTO users (name, email, password, phone, role) VALUES ('Adam Farhan', 'adam.farhan@gmail.com', '$2y$12$aCWctNFxbGD1xHxd7qm16OXx0SB2kXMRY/akBeG2UFgL1j.DTfYOa', '60129876543', 'client') ON DUPLICATE KEY UPDATE name = VALUES(name), phone = VALUES(phone), role = VALUES(role);
INSERT INTO users (name, email, password, phone, role) VALUES ('Siti Aisyah', 'siti.aisyah@gmail.com', '$2y$12$aCWctNFxbGD1xHxd7qm16OXx0SB2kXMRY/akBeG2UFgL1j.DTfYOa', '60139876543', 'client') ON DUPLICATE KEY UPDATE name = VALUES(name), phone = VALUES(phone), role = VALUES(role);
INSERT INTO users (name, email, password, phone, role) VALUES ('Chloe Tan', 'chloe.tan@gmail.com', '$2y$12$aCWctNFxbGD1xHxd7qm16OXx0SB2kXMRY/akBeG2UFgL1j.DTfYOa', '60149876543', 'client') ON DUPLICATE KEY UPDATE name = VALUES(name), phone = VALUES(phone), role = VALUES(role);
INSERT INTO users (name, email, password, phone, role) VALUES ('Marcus Wong', 'marcus.wong@gmail.com', '$2y$12$aCWctNFxbGD1xHxd7qm16OXx0SB2kXMRY/akBeG2UFgL1j.DTfYOa', '60169876543', 'client') ON DUPLICATE KEY UPDATE name = VALUES(name), phone = VALUES(phone), role = VALUES(role);
INSERT INTO users (name, email, password, phone, role) VALUES ('Nur Aina Syafiah', 'aina.syafiah@gmail.com', '$2y$12$aCWctNFxbGD1xHxd7qm16OXx0SB2kXMRY/akBeG2UFgL1j.DTfYOa', '60179876543', 'client') ON DUPLICATE KEY UPDATE name = VALUES(name), phone = VALUES(phone), role = VALUES(role);
INSERT INTO users (name, email, password, phone, role) VALUES ('Bryan Lim', 'bryan.lim@gmail.com', '$2y$12$aCWctNFxbGD1xHxd7qm16OXx0SB2kXMRY/akBeG2UFgL1j.DTfYOa', '60189876543', 'client') ON DUPLICATE KEY UPDATE name = VALUES(name), phone = VALUES(phone), role = VALUES(role);
INSERT INTO users (name, email, password, phone, role) VALUES ('Haziq Izzat', 'haziq.izzat@gmail.com', '$2y$12$aCWctNFxbGD1xHxd7qm16OXx0SB2kXMRY/akBeG2UFgL1j.DTfYOa', '60199876543', 'client') ON DUPLICATE KEY UPDATE name = VALUES(name), phone = VALUES(phone), role = VALUES(role);

-- 2. Services
INSERT INTO services (user_id, category_id, title, description, price, availability) VALUES (9, 1, 'Calculus & Python Programming 1-on-1 Coaching', 'Patient step-by-step coaching for undergraduate Calculus I & II, Linear Algebra, and Python fundamentals. Includes past-year exam questions walkthrough, assignment debugging, and customized revision formula sheets. Sessions held on campus library discussion rooms or via Google Meet.', 25.00, 1);
INSERT INTO services (user_id, category_id, title, description, price, availability) VALUES (9, 1, 'Data Structures & Java Lab Assignment Guidance', 'Assistance for Object-Oriented Programming (OOP), Linked Lists, Trees, Stacks, Queues, and Big-O algorithm analysis. Clear explanations to help you understand core concepts and pass your practical programming assessments with confidence.', 30.00, 1);
INSERT INTO services (user_id, category_id, title, description, price, availability) VALUES (10, 2, 'Poster Design, Event Flyers & Social Media Carousels', 'Eye-catching, modern digital artwork tailored for student clubs, campus orientations, society conferences, and local business promotions. Delivered in high-res PNG, PDF print-ready format, and editable Canva/Photoshop source files within 24-48 hours.', 35.00, 1);
INSERT INTO services (user_id, category_id, title, description, price, availability) VALUES (10, 2, 'Pitch Deck & Presentation Slide Makeover (PowerPoint / Canva)', 'Transform cluttered, text-heavy academic or startup slides into clean, visually engaging presentations. Includes custom infographics, consistent typography, clean layouts, and animated transitions to impress your lecturers or investors.', 45.00, 1);
INSERT INTO services (user_id, category_id, title, description, price, availability) VALUES (10, 2, 'Minimalist Brand Logo & Identity Kit for Student Startups', 'Professional vector logo design including primary mark, secondary badge, curated color palette with HEX codes, typography pairing, and mockups. Ideal for emerging food vendors, apparel brands, and student tech ventures.', 80.00, 1);
INSERT INTO services (user_id, category_id, title, description, price, availability) VALUES (11, 3, 'Laptop Reformatting, SSD Upgrade & Thermal Paste Servicing', 'Complete laptop tune-up: dust blowout, Arctic MX-4 premium thermal paste application for lower CPU/GPU temperatures, NVMe/SATA SSD installation, and clean OS reinstallation (Windows 10/11 or macOS). Free preliminary diagnosis via WhatsApp.', 45.00, 1);
INSERT INTO services (user_id, category_id, title, description, price, availability) VALUES (11, 3, 'Smartphone Screen & High-Capacity Battery Replacement', 'Fast on-campus diagnosis and repair for iPhone, Samsung, Xiaomi, and Realme models. Replacement of cracked OLED/LCD screens and degraded batteries with quality tested parts. Same-day turnaround available.', 75.00, 1);
INSERT INTO services (user_id, category_id, title, description, price, availability) VALUES (11, 3, 'Mechanical Keyboard Switch Lubing, Custom Cable & Deep Cleaning', 'Keyboard enthusiast service: Krytox 205g0 switch lubing, stabilizer holee mod & balancing, ultrasonic keycap wash, and custom coil cable assembly for a silent, thocky typing experience.', 35.00, 0);
INSERT INTO services (user_id, category_id, title, description, price, availability) VALUES (12, 4, 'Urgent Campus Parcel, Food & Document Dispatch Runner', 'Motorcycle dispatch service covering campus residential colleges (Mahallah), faculty offices, parcel collection lockers, and nearby food stalls. Direct door-to-door delivery with live WhatsApp location sharing.', 6.00, 1);
INSERT INTO services (user_id, category_id, title, description, price, availability) VALUES (12, 4, 'Late-Night Printing, Colour Plotting & Spiral Binding Runner', 'Save time during final submissions! Send your PDF files via WhatsApp and I will handle high-quality digital printing, wire-o / comb binding, architectural plotting, and deliver the final copies directly to your faculty room.', 12.00, 1);
INSERT INTO services (user_id, category_id, title, description, price, availability) VALUES (13, 5, 'Outdoor Graduation & Convocation Portrait Photoshoot (1 Hour)', 'Celebrate your milestone with aesthetic portraits shot on Sony A7III full-frame mirrorless. Includes 1-hour outdoor campus session, 20 color-graded high-resolution digital photos, full print rights, and fast cloud drive delivery in 48 hours.', 120.00, 1);
INSERT INTO services (user_id, category_id, title, description, price, availability) VALUES (13, 5, 'Club Annual Dinner & Society Event Photography Package', 'Full event coverage for club inductions, gala dinners, sports tournaments, and award nights. Professional flash photography capturing stage presentations, VIP arrivals, candid crowd moments, and group portraits.', 180.00, 1);
INSERT INTO services (user_id, category_id, title, description, price, availability) VALUES (14, 6, 'Hostel Wi-Fi Booster & Network Connectivity Troubleshooting', 'Fix slow internet, packet loss, DNS errors, and weak Wi-Fi signals in college dorm rooms. Setup and configuration of portable Wi-Fi repeaters, Ethernet cable crimping, and personal VPN guidance.', 25.00, 1);
INSERT INTO services (user_id, category_id, title, description, price, availability) VALUES (14, 6, 'Complete Malware Removal, Windows 11 Optimization & Backup', 'Remove stubborn adware, crypto miners, spyware, and background bloatware slowing down your PC. Optimize startup programs, configure automatic Google Drive backups, and ensure your system is secure and responsive.', 40.00, 1);
INSERT INTO services (user_id, category_id, title, description, price, availability) VALUES (15, 7, 'Resume, CV & Internship Cover Letter ATS Optimization', 'Professional review by a communications major with prior HR internship experience. Rewriting bullet points into impactful action-result statements, tailoring keywords to pass Applicant Tracking Systems (ATS), and fixing formatting errors.', 20.00, 1);
INSERT INTO services (user_id, category_id, title, description, price, availability) VALUES (15, 7, 'Professional Badminton Racquet Restringing & Custom Grip Setup', 'Precision electronic tension restringing for badminton racquets (22 lbs to 30 lbs). Yonex BG66 Ultimax, Nanogy, and Aerobite string selections available with cushion wrap and tacky overgrip installation.', 28.00, 1);
INSERT INTO services (user_id, category_id, title, description, price, availability) VALUES (16, 1, 'Engineering Statics, Dynamics & Fluid Mechanics Problem-Solving', 'Intensive problem-solving sessions for Mechanical and Civil Engineering students. Mastery of free-body diagrams, shear force & bending moment diagrams, kinematics, and Bernoulli equation applications.', 35.00, 1);
INSERT INTO services (user_id, category_id, title, description, price, availability) VALUES (2, 6, 'Full-Stack Web App Development & Bug Fixing (PHP, MySQL, JS)', 'Hands-on assistance for web development assignments and personal projects. Responsive UI styling, database normalization, PHP authentication, RESTful APIs, and local development environment (Laragon / XAMPP) troubleshooting.', 60.00, 1);
INSERT INTO services (user_id, category_id, title, description, price, availability) VALUES (2, 6, 'Final Year Project (FYP) Architecture & Database Design Review', '1-on-1 consultation for software engineering final year projects. Review of entity relationship diagrams (ERD), normalized schema design, security best practices (SQL injection prevention, password hashing), and code refactoring.', 50.00, 1);

-- 3. Reviews
INSERT INTO reviews (service_id, client_id, rating, review_text) VALUES (1, 18, 5, 'Ahmad is an incredible tutor! Needed urgent peer tutoring right before my Calculus II midterm. His explanations of integration techniques and Python loops were so clear. Aced the exam with an A-!');
INSERT INTO reviews (service_id, client_id, rating, review_text) VALUES (1, 17, 5, 'Very patient tutor. Helped me debug my Python semester project and taught me how to structure clean functions. Highly recommended for beginners.');
INSERT INTO reviews (service_id, client_id, rating, review_text) VALUES (3, 19, 5, 'Nurul delivered our club orientation banner and Instagram carousel in less than 24 hours. The aesthetics were top notch and everyone loved the visuals!');
INSERT INTO reviews (service_id, client_id, rating, review_text) VALUES (4, 22, 5, 'Turned our boring 30-slide presentation into a slick, modern investor pitch deck. Our lecturer praised the design in front of the whole lecture hall.');
INSERT INTO reviews (service_id, client_id, rating, review_text) VALUES (6, 20, 5, 'My laptop suddenly blue-screened right before assignment submission. Kevin fixed the operating system and cleaned out the thermal paste in under 3 hours. Absolute lifesaver!');
INSERT INTO reviews (service_id, client_id, rating, review_text) VALUES (7, 23, 5, 'Fixed my cracked iPhone screen on campus during lunch hour. Tested touch responsiveness and TrueTone works perfectly. Much cheaper than official service centers.');
INSERT INTO reviews (service_id, client_id, rating, review_text) VALUES (9, 21, 5, 'Fast and reliable runner! Delivered my heavy package from the main campus courier station straight to my residential college door in the rain without any issues.');
INSERT INTO reviews (service_id, client_id, rating, review_text) VALUES (10, 4, 5, 'Saved me from failing our group design submission deadline at 2 AM. Printed full color architectural drawings and bound them neatly.');
INSERT INTO reviews (service_id, client_id, rating, review_text) VALUES (11, 22, 5, 'Farah has an amazing eye for lighting, natural poses, and campus backdrop spots. The graduation photos turned out magazine-quality!');
INSERT INTO reviews (service_id, client_id, rating, review_text) VALUES (12, 19, 5, 'Covered our Computer Science Society annual grand dinner. Captures every emotion, stage award, and group photo with crystal clear sharpness.');
INSERT INTO reviews (service_id, client_id, rating, review_text) VALUES (13, 17, 4, 'Danial identified why our block had terrible Wi-Fi dead spots and configured a repeater for our room. Ping dropped from 180ms to 24ms.');
INSERT INTO reviews (service_id, client_id, rating, review_text) VALUES (14, 18, 5, 'Removed suspicious adware popups that were hijacking Chrome. My laptop boots in 8 seconds now. Very friendly and knowledgeable!');
INSERT INTO reviews (service_id, client_id, rating, review_text) VALUES (15, 23, 5, 'Siti restructured my CV to pass automated ATS screening. Received two internship interview invitations within a week of applying!');
INSERT INTO reviews (service_id, client_id, rating, review_text) VALUES (16, 20, 5, 'Restrung my Yonex Astrox at 27 lbs with BG66 Ultimax. Crisp sound and fantastic tension retention during our campus friendly match.');
INSERT INTO reviews (service_id, client_id, rating, review_text) VALUES (17, 4, 5, 'Priya broke down 3D moment calculations and shear stress distribution into simple diagrams. Passed my engineering quiz with flying colors!');
INSERT INTO reviews (service_id, client_id, rating, review_text) VALUES (18, 17, 5, 'Ayman resolved our PHP session fixation and PDO query bugs within an hour. Excellent explanations and clean code practices.');
INSERT INTO reviews (service_id, client_id, rating, review_text) VALUES (19, 20, 5, 'The database schema review prevented major redundancy errors before our proposal defense. Got great feedback from our academic supervisor!');
